
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class ChatGUI extends javax.swing.JFrame implements Observer{
    
    Handler Handler;

    public ChatGUI(Handler Handler) {
        this.Handler = Handler;
        Handler.addObserver(this);
        initComponents();
    }
    
    
    
    public void update(Observable o, Object arg) {
            final Object finalArg = arg;
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    chatFrame.append(finalArg.toString());
                    chatFrame.append("\n");
                }
            });
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatFrame = new javax.swing.JTextArea();
        inputLine = new javax.swing.JTextField();
        sendLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatFrame.setEditable(false);
        chatFrame.setColumns(20);
        chatFrame.setRows(5);
        jScrollPane1.setViewportView(chatFrame);

        inputLine.setText("Ketikan chat anda disini..");
        inputLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLineActionPerformed(evt);
            }
        });
        inputLine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputLineFocusGained(evt);
            }
        });

        sendLine.setText("Kirim");
        sendLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLine, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendLine, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLine)
                    .addComponent(sendLine, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLineActionPerformed
        // TODO add your handling code here:
        Handler.send(inputLine.getText());
        inputLine.setText("");
    }//GEN-LAST:event_inputLineActionPerformed

    private void sendLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLineActionPerformed
        // TODO add your handling code here:
        Handler.send(inputLine.getText());
        inputLine.setText("");
    }//GEN-LAST:event_sendLineActionPerformed

    private void inputLineFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputLineFocusGained
        // TODO add your handling code here:
        inputLine.setText("");
    }//GEN-LAST:event_inputLineFocusGained

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatFrame;
    private javax.swing.JTextField inputLine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendLine;
    // End of variables declaration//GEN-END:variables
}


